#define sqrt(x) __builtin_sqrt(x)
#define abs(x) __builtin_abs(x)
#define fabs(x) __builtin_fabs(x)
#define floor(x) __builtin_floor(x)
#define ceil(x) __builtin_ceil(x)
#define pow(x, y) __builtin_pow(x, y)
#define sin(x) __builtin_sin(x)
#define cos(x) __builtin_cos(x)
#define tan(x) __builtin_tan(x)
#define log(x) __builtin_log(x)
#define exp(x) __builtin_exp(x)